#!/bin/sh

#############################################################################
##
##  cloud azure defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# https://learn.microsoft.com/en-us/legal/marketplace/certification-policies#20033-linux

# Supported
readonly CADI_SUPPORTED_ARCHS="aarch64,x86,x86_64"
readonly CADI_SUPPORTED_CLOUD_INIT_DATASOURCES="Azure"
readonly CADI_SUPPORTED_CONFIGURATION_TOOLS="cloud-init,none,tiny-cloud"
readonly CADI_SUPPORTED_IPV4=true
readonly CADI_SUPPORTED_IPV6=true
readonly CADI_SUPPORTED_IPV4_IPV6=true
readonly CADI_SUPPORTED_NTP_METHODS="pools,ptp,servers"
readonly CADI_SUPPORTED_OS_BOOT_DISK_SWAP=false
readonly CADI_SUPPORTED_OS_FILESYSTEMS="ext4,xfs"


# Defaults
readonly CADI_DEFAULT_ARCH="x86_64"
readonly CADI_DEFAULT_NTP_METHOD="ptp"
readonly CADI_DEFAULT_OS_FILESYSTEM="ext4"


# Additional
readonly CADI_CHRONY_INITSTEPSLEW_THRESHOLD=30
readonly CADI_CHRONY_MAKESTEP_THRESHOLD=1
readonly CADI_CHRONY_MAKESTEP_LIMIT=-1
readonly CADI_CLOUD_INIT_USES_FS="ISO"
readonly CADI_PTP_DEVICE_NAME="/dev/ptp_hyperv"
readonly CADI_PTP_DEVICE_TYPE="hyperv"
readonly CADI_PTP_DPOLL=-2
readonly CADI_PTP_OFFSET=0.0
readonly CADI_PTP_POLL=3
readonly CADI_PTP_STRATUM=2
