#!/bin/sh

#############################################################################
##
##  cloud azure x86_64-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# https://learn.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-generic

# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="tiny-power-button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="bios,secure-uefi,uefi,hybrid"
readonly CADI_SUPPORTED_BOOTLOADERS_BIOS="grub,syslinux,limine"
readonly CADI_SUPPORTED_BOOTLOADERS_HYBRID="grub,limine"
readonly CADI_SUPPORTED_BOOTLOADERS_SECURE_UEFI="grub"
readonly CADI_SUPPORTED_BOOTLOADERS_UEFI="grub,limine"
readonly CADI_SUPPORTED_CLOCKSOURCES="acpi_pm,hyperv,tsc"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="normal,normal_and_serial,serial"
readonly CADI_SUPPORTED_CONSOLE_GRAPHICS_DRIVERS="generic,hyperv,simpledrm"
readonly CADI_SUPPORTED_CONSOLE_KEYBOARD_TYPES="generic,hyperv,ps2"
readonly CADI_SUPPORTED_CONSOLE_OUTPUT_TYPES="generic,graphics,text"
readonly CADI_SUPPORTED_DHCP_CLIENTS="dhclient"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="gpt,mbr"
readonly CADI_SUPPORTED_NETWORK_DRIVERS="generic,hyperv,mana,mlx4_en,mlx5_core"
readonly CADI_SUPPORTED_OS_BOOT_DISK_SWAP=false
readonly CADI_SUPPORTED_OS_BOOT_NETWORK_DRIVERS="none"
readonly CADI_SUPPORTED_OS_DEVICE_MEDIAS="disk"
readonly CADI_SUPPORTED_OS_DEVICE_TYPES="generic,hyperv,nvme"
readonly CADI_SUPPORTED_OS_SEPARATE_BOOT_PARTITION=true
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_BASE_NAME="ttyS"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_NUMBER="0"
readonly CADI_SUPPORTED_STORAGE_DRIVERS="generic,hyperv,nvme"


# Defaults
readonly CADI_DEFAULT_BOOT_TYPE="bios"
readonly CADI_DEFAULT_BOOTLOADER="grub"
readonly CADI_DEFAULT_CLOCKSOURCE="hyperv"
readonly CADI_DEFAULT_CONSOLE_DEVICE_TYPE="normal_and_serial"
readonly CADI_DEFAULT_CONSOLE_GRAPHICS_DRIVER="hyperv"
readonly CADI_DEFAULT_CONSOLE_KEYBOARD_TYPE="generic"
readonly CADI_DEFAULT_CONSOLE_OUTPUT_TYPE="text"
readonly CADI_DEFAULT_NETWORK_DRIVER="generic"
readonly CADI_DEFAULT_OS_DEVICE_TYPE="hyperv"
readonly CADI_DEFAULT_STORAGE_DRIVER="generic"


# Additional
readonly CADI_ADDITIONAL_INITRAMFS_MODULES="hv_utils,hv_vmbus"
readonly CADI_DISK_IMAGE_FORMAT="vhd"
readonly CADI_PACKAGES_ADDITIONAL="hvtools py3-passlib"
# Size of packages & all their dependencies (in MB)
readonly CADI_PACKAGES_ADDITIONAL_SIZE=1
readonly CADI_PACKAGES_EXTRA="nvme-cli"
# Size of package & all their dependencies (in MB)
readonly CADI_PACKAGES_EXTRA_SIZE=1
