#!/bin/sh

#############################################################################
##
##  cloud generic defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Supported
readonly CADI_SUPPORTED_ARCHS="aarch64,x86,x86_64"
#readonly CADI_SUPPORTED_CLOUD_INIT_DATASOURCES="NoCloud,ConfigDrive,Akamai,AliYun,Azure,Bigstep,Ec2,Exoscale,GCE,Hetzner,IBMCloud,OpenStack,Oracle,RbxCloud,Scaleway,UpCloud,Vultr"
readonly CADI_SUPPORTED_CLOUD_INIT_DATASOURCES="NoCloud,ConfigDrive,AliYun,Azure,Bigstep,Ec2,Exoscale,GCE,Hetzner,IBMCloud,OpenStack,Oracle,RbxCloud,Scaleway,UpCloud,Vultr,None"
readonly CADI_SUPPORTED_CONFIGURATION_TOOLS="cloud-init,none"
readonly CADI_SUPPORTED_IPV4=true
readonly CADI_SUPPORTED_IPV6=true
readonly CADI_SUPPORTED_IPV4_IPV6=true
readonly CADI_SUPPORTED_NTP_METHODS="pools,servers"
readonly CADI_SUPPORTED_OS_FILESYSTEMS="ext4,xfs"


# Defaults
readonly CADI_DEFAULT_ARCH="x86_64"
readonly CADI_DEFAULT_OS_FILESYSTEM="ext4"


# Additional
readonly CADI_CLOUD_INIT_USES_FS="ISO,VFAT"
