version: 2
ethernets:
  eth0:
    wakeonlan: true
    match:
      macaddress: '52:54:00:12:34:56'
      name: eth0
    addresses:
      - 172.19.11.5/24
      - fd7b:dec0:d00d:11::5/64
    gateway4: 172.19.11.1
    gateway6: fd7b:dec0:d00d:11::1
