#!/bin/sh

#############################################################################
##
##  cloud hetzner x86_64-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="tiny-power-button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="bios"
readonly CADI_SUPPORTED_BOOTLOADERS_BIOS="grub,syslinux,limine"
readonly CADI_SUPPORTED_CLOCKSOURCES="generic,acpi_pm,kvm,tsc"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="none"
readonly CADI_SUPPORTED_CONSOLE_GRAPHICS_DRIVERS="none"
readonly CADI_SUPPORTED_CONSOLE_KEYBOARD_TYPES="none"
readonly CADI_SUPPORTED_CONSOLE_OUTPUT_TYPES="none"
readonly CADI_SUPPORTED_CRYPTO_DEVICES="virtio"
readonly CADI_SUPPORTED_DHCP_CLIENTS="dhclient"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="mbr"
readonly CADI_SUPPORTED_NETWORK_DRIVERS="virtio-net"
readonly CADI_SUPPORTED_OS_BOOT_NETWORK_DRIVERS="none"
readonly CADI_SUPPORTED_OS_DEVICE_MEDIAS="generic,disk,ssd"
readonly CADI_SUPPORTED_OS_DEVICE_TYPES="virtio-blk"
readonly CADI_SUPPORTED_OS_SEPARATE_BOOT_PARTITION=true
readonly CADI_SUPPORTED_RNGS="virtio"
readonly CADI_SUPPORTED_STORAGE_DRIVERS="virtio-blk"


# Defaults
readonly CADI_DEFAULT_BOOTLOADER="grub"
readonly CADI_DEFAULT_CLOCKSOURCE="kvm"
readonly CADI_DEFAULT_OS_DEVICE_MEDIA="generic"


# Additional
readonly CADI_CLOUD_CLI_PACKAGES="hcloud"
# Size of packages & all their dependencies (in MB)
readonly CADI_CLOUD_CLI_PACKAGES_SIZE=12
readonly CADI_DISK_IMAGE_COMPRESSION="gzip"
readonly CADI_DISK_IMAGE_FORMAT="qcow2"
readonly CADI_PACKAGES_EXTRA="nvme-cli"
# Size of package & all their dependencies (in MB)
readonly CADI_PACKAGES_EXTRA_SIZE=1
