#!/bin/sh

#############################################################################
##
##  physical-pc-x86_64-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="bios,hybrid,secure-uefi,uefi"
readonly CADI_SUPPORTED_BOOTLOADERS_BIOS="grub,limine,syslinux"
readonly CADI_SUPPORTED_BOOTLOADERS_HYBRID="grub,limine"
readonly CADI_SUPPORTED_BOOTLOADERS_SECURE_UEFI="grub"
readonly CADI_SUPPORTED_BOOTLOADERS_UEFI="grub,limine,uki"
readonly CADI_SUPPORTED_CLOCKSOURCES="generic,acpi_pm,tsc"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="generic,normal,normal_and_serial,serial"
readonly CADI_SUPPORTED_CONSOLE_GRAPHICS_DRIVERS="generic,amd,bochs,i915,nouveau,radeon,simpledrm"
readonly CADI_SUPPORTED_CONSOLE_KEYBOARD_TYPES="generic,none,ps2,usb"
readonly CADI_SUPPORTED_CONSOLE_OUTPUT_TYPES="generic,graphics,text"
readonly CADI_SUPPORTED_CRYPTO_DEVICES="ccp"
readonly CADI_SUPPORTED_DHCP_CLIENTS="generic,dhclient,dhcpcd,udhcpc"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="gpt,mbr"
readonly CADI_SUPPORTED_NETWORK_DRIVERS="generic,alx,e1000,e1000e,i40e,ice,igb,igbvf,igc,ixgb,ixgbe,ixgbevf,nvidia,r8169,tg3"
readonly CADI_SUPPORTED_OS_BOOT_NETWORK_DRIVERS="generic,alx,e1000,e1000e,i40e,ice,igb,igbvf,igc,ixgb,ixgbe,ixgbevf,nvidia,r8169,tg3"
readonly CADI_SUPPORTED_OS_DEVICE_MEDIAS="generic,disk,flash,sdcard,ssd"
readonly CADI_SUPPORTED_OS_DEVICE_TYPES="generic,nvme,sata,scsi,sd,usb"
readonly CADI_SUPPORTED_OS_SEPARATE_BOOT_PARTITION=true
readonly CADI_SUPPORTED_RNGS="amd,intel"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_BASE_NAME="ttyS"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_NUMBER="0"
readonly CADI_SUPPORTED_STORAGE_DRIVERS="generic,nvme,sata,scsi,sd,usb"


# Defaults
readonly CADI_DEFAULT_BOOT_TYPE="bios"
readonly CADI_DEFAULT_BOOTLOADER="grub"
readonly CADI_DEFAULT_CONSOLE_DEVICE_TYPE="normal"
readonly CADI_DEFAULT_CONSOLE_GRAPHICS_DRIVER="generic"
readonly CADI_DEFAULT_CONSOLE_KEYBOARD_TYPE="both"
readonly CADI_DEFAULT_CONSOLE_OUTPUT_TYPE="text"
readonly CADI_DEFAULT_DHCP_CLIENT="dhcpcd"
readonly CADI_DEFAULT_NETWORK_DRIVER="generic"
readonly CADI_DEFAULT_OS_BOOT_NETWORK_DRIVER="generic"
readonly CADI_DEFAULT_OS_DEVICE_MEDIA="disk"
readonly CADI_DEFAULT_OS_DEVICE_TYPE="sata"
readonly CADI_DEFAULT_STORAGE_DRIVERS="generic"


# Additional
readonly CADI_PACKAGES_ADDITIONAL="cpufrequtils,ethtool,irqbalance"
# Size of package & all their dependencies (in MB)
readonly CADI_PACKAGES_ADDITIONAL_SIZE=6
readonly CADI_PACKAGES_EXTRA="fstrim,hd-idle,hdparm,lm-sensors,smartmontools"
# Size of package & all their dependencies (in MB)
readonly CADI_PACKAGES_EXTRA_SIZE=7
