#!/bin/sh

#############################################################################
##
##  physical-pc-x86_64-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="bios,secure-uefi,uefi,hybrid"
readonly CADI_SUPPORTED_BOOTLOADERS_BIOS="grub,syslinux,limine"
readonly CADI_SUPPORTED_BOOTLOADERS_HYBRID="grub,limine"
readonly CADI_SUPPORTED_BOOTLOADERS_SECURE_UEFI="grub"
readonly CADI_SUPPORTED_BOOTLOADERS_UEFI="grub,limine,uki"
readonly CADI_SUPPORTED_CLOCKSOURCES="acpi_pm,tsc"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="normal,normal_and_serial,serial"
readonly CADI_SUPPORTED_CONSOLE_GRAPHICS_DRIVERS="generic,amd,bochs,i915,nouveau,radeon,simpledrm"
readonly CADI_SUPPORTED_CONSOLE_KEYBOARD_TYPES="both,ps2,usb"
readonly CADI_SUPPORTED_CONSOLE_OUTPUT_TYPES="generic,graphics,text"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="gpt,mbr"
readonly CADI_SUPPORTED_OS_DEVICE_MEDIAS="disk,flash,sdcard,ssd"
readonly CADI_SUPPORTED_OS_DEVICE_TYPES="nvme,sata,scsi,sd,usb"
readonly CADI_SUPPORTED_OS_SEPARATE_BOOT_PARTITION=true
readonly CADI_SUPPORTED_RNGS="amd,intel"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_BASE_NAME="ttyS"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_NUMBER="0"


# Defaults
readonly CADI_DEFAULT_BOOT_TYPE="bios"
readonly CADI_DEFAULT_BOOTLOADER="grub"
readonly CADI_DEFAULT_CONSOLE_DEVICE_TYPE="normal"
readonly CADI_DEFAULT_CONSOLE_GRAPHICS_DRIVER="generic"
readonly CADI_DEFAULT_CONSOLE_KEYBOARD_TYPE="both"
readonly CADI_DEFAULT_CONSOLE_OUTPUT_TYPE="generic"
readonly CADI_DEFAULT_OS_DEVICE_MEDIA="disk"
readonly CADI_DEFAULT_OS_DEVICE_TYPE="sata"


# Additional
readonly CADI_PACKAGES_ADDITIONAL_LIST="cpufrequtils,ethtool,irqbalance"
readonly CADI_PACKAGES_EXTRA_LIST="fstrim,hd-idle,hdparm,lm-sensors,smartmontools"
