#!/bin/sh

#############################################################################
##
##  cloud digitalocean defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# https://docs.digitalocean.com/products/droplets/how-to/connect-with-console/
# https://docs.digitalocean.com/products/images/custom-images/how-to/upload/

# Supported
readonly CADI_SUPPORTED_ARCHS="x86,x86_64"
readonly CADI_SUPPORTED_CLOUD_INIT_DATASOURCES="ConfigDrive"
readonly CADI_SUPPORTED_CONFIGURATION_TOOLS="cloud-init,none"
readonly CADI_SUPPORTED_IPV4=true
readonly CADI_SUPPORTED_IPV6=true
readonly CADI_SUPPORTED_IPV4_IPV6=true
readonly CADI_SUPPORTED_NTP_METHODS="pools,servers"
readonly CADI_SUPPORTED_OS_BOOT_DISK_SWAP=true
readonly CADI_SUPPORTED_OS_DEVICE_TYPES="nvme,virtio-blk"
readonly CADI_SUPPORTED_OS_FILESYSTEMS="ext4,xfs"
readonly CADI_SUPPORTED_OS_LUKS_ENCRYPTION=false


# Defaults
readonly CADI_DEFAULT_ARCH="x86_64"
readonly CADI_DEFAULT_OS_DEVICE_TYPE="virtio-blk"
readonly CADI_DEFAULT_OS_FILESYSTEM="ext4"
readonly CADI_DEFAULT_NTP_METHOD="pools"


# Additional
readonly CADI_CHRONY_INITSTEPSLEW_THRESHOLD=30
readonly CADI_CHRONY_MAKESTEP_THRESHOLD=1
readonly CADI_CHRONY_MAKESTEP_LIMIT=-1
readonly CADI_CLOUD_INIT_DISABLE_VENDORDATA=true
