#!/bin/sh

#############################################################################
##
##  cloud digitalocean x86-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# https://docs.digitalocean.com/products/droplets/how-to/connect-with-console/

# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="button,tiny-power-button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="bios,hybrid"
readonly CADI_SUPPORTED_BOOTLOADERS_BIOS="grub,syslinux,limine"
readonly CADI_SUPPORTED_BOOTLOADERS_HYBRID="grub,limine"
readonly CADI_SUPPORTED_CLOCKSOURCES="acpi_pm,kvm,tsc"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="none"
readonly CADI_SUPPORTED_CONSOLE_GRAPHICS_DRIVERS="none"
readonly CADI_SUPPORTED_CONSOLE_KEYBOARD_TYPES="none"
readonly CADI_SUPPORTED_CONSOLE_OUTPUT_TYPES="none"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="mbr"
readonly CADI_SUPPORTED_OS_DEVICE_MEDIAS="disk,ssd"
readonly CADI_SUPPORTED_OS_SEPARATE_BOOT_PARTITION=true
readonly CADI_SUPPORTED_VIRTIO_CRYPTO=false


# Defaults
readonly CADI_DEFAULT_ACPI_BUTTON="tiny-power-button"
readonly CADI_DEFAULT_BOOT_TYPE="bios"
readonly CADI_DEFAULT_BOOTLOADER="grub"
readonly CADI_DEFAULT_OS_DEVICE_MEDIA="disk"


# Additional
readonly CADI_DISK_IMAGE_FORMAT="qcow2"
readonly CADI_DISK_IMAGE_COMPRESSION="gzip"
readonly CADI_PACKAGES_ADDITIONAL="irqbalance"
# Size of packages & all their dependencies (in MB)
readonly CADI_PACKAGES_ADDITIONAL_SIZE=5
readonly CADI_CLOUD_CLI_PACKAGES="doctl"
readonly CADI_CLOUD_CLI_PACKAGES_NOTPRESENTIN="v3.13,v3.14,v3.15"
# Size of packages & all their dependencies (in MB)
readonly CADI_CLOUD_CLI_PACKAGES_SIZE=23
readonly CADI_PACKAGES_EXTRA="nvme-cli"
# Size of package & all their dependencies (in MB)
readonly CADI_PACKAGES_EXTRA_SIZE=1
