#!/bin/sh

#############################################################################
##
##  virtual hyperv x86-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="tiny-power-button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="bios,hybrid"
readonly CADI_SUPPORTED_BOOTLOADERS_BIOS="grub,limine,syslinux"
readonly CADI_SUPPORTED_BOOTLOADERS_HYBRID="grub,limine"
readonly CADI_SUPPORTED_CLOCKSOURCES="generic,acpi_pm,hyperv,tsc"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="normal,normal_and_serial,serial"
readonly CADI_SUPPORTED_CONSOLE_GRAPHICS_DRIVERS="generic,hyperv,simpledrm"
readonly CADI_SUPPORTED_CONSOLE_KEYBOARD_TYPES="generic,hyperv,none,ps2,usb"
readonly CADI_SUPPORTED_CONSOLE_OUTPUT_TYPES="graphics,text"
readonly CADI_SUPPORTED_CRYPTO_DEVICES="none"
readonly CADI_SUPPORTED_DHCP_CLIENTS="dhclient,dhcpcd,udhcpc"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="gpt,mbr"
readonly CADI_SUPPORTED_NETWORK_DRIVERS="hyperv"
readonly CADI_SUPPORTED_OS_BOOT_NETWORK_DRIVERS="none"
readonly CADI_SUPPORTED_OS_DEVICE_MEDIAS="generic,disk,ssd"
readonly CADI_SUPPORTED_OS_DEVICE_TYPES="generic,hyperv,nvme"
readonly CADI_SUPPORTED_OS_SEPARATE_BOOT_PARTITION=true
readonly CADI_SUPPORTED_RNGS="none"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_BASE_NAME="ttyS"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_NUMBER="0"
readonly CADI_SUPPORTED_STORAGE_DRIVERS="generic,hyperv,nvme"


# Defaults
readonly CADI_DEFAULT_BOOT_TYPE="bios"
readonly CADI_DEFAULT_BOOTLOADER="grub"
readonly CADI_DEFAULT_CLOCKSOURCE="hyperv"
readonly CADI_DEFAULT_CONSOLE_DEVICE_TYPE="normal_and_serial"
readonly CADI_DEFAULT_CONSOLE_GRAPHICS_DRIVER="hyperv"
readonly CADI_DEFAULT_CONSOLE_KEYBOARD_TYPE="generic"
readonly CADI_DEFAULT_CONSOLE_OUTPUT_TYPE="graphics"
readonly CADI_DEFAULT_DHCP_CLIENT="dhcpcd"
readonly CADI_DEFAULT_DISK_IMAGE_PARTITIONING_TYPE="mbr"
readonly CADI_DEFAULT_OS_DEVICE_MEDIA="generic"
readonly CADI_DEFAULT_OS_DEVICE_TYPE="hyperv"
readonly CADI_DEFAULT_STORAGE_DRIVER="generic"


# Additional
readonly CADI_ADDITIONAL_NON_INITRAMFS_MODULES="hv_balloon,hv_utils,hv_vmbus"
readonly CADI_HYPERVISOR_AGENT_PACKAGES="hvtools"
readonly CADI_HYPERVISOR_AGENT_PACKAGES_SIZE=1
