#!/bin/sh

#############################################################################
##
##  cloud aws defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Supported
readonly CADI_SUPPORTED_ARCHS="aarch64,x86,x86_64"
readonly CADI_SUPPORTED_CLOUD_INIT_DATASOURCES="Ec2"
readonly CADI_SUPPORTED_CLOUD_INIT_NETWORK_HOTPLUG=true
readonly CADI_SUPPORTED_CONFIGURATION_TOOLS="cloud-init,none,tiny-cloud"
readonly CADI_SUPPORTED_DHCP_CLIENT="dhclient"
readonly CADI_SUPPORTED_IPV4=true
readonly CADI_SUPPORTED_IPV6=true
readonly CADI_SUPPORTED_IPV4_IPV6=true
readonly CADI_SUPPORTED_NTP_METHODS="pools,servers,servers_and_pools"
readonly CADI_SUPPORTED_OS_BOOT_DISK_SWAP=false
readonly CADI_SUPPORTED_OS_FILESYSTEMS="ext4,xfs"
readonly CADI_SUPPORTED_OS_LUKS_ENCRYPTION=false


# Defaults
readonly CADI_DEFAULT_ARCH="x86_64"
readonly CADI_DEFAULT_NTP_METHOD="servers_and_pools"
readonly CADI_DEFAULT_OS_FILESYSTEM="ext4"


# Additional
readonly CADI_CHRONY_INITSTEPSLEW_THRESHOLD=30
readonly CADI_CHRONY_MAKESTEP_THRESHOLD=1
readonly CADI_CHRONY_MAKESTEP_LIMIT=-1
readonly CADI_DHCP_CLIENT="dhcpcd"
readonly CADI_NTP_IPV4_SERVERS="169.254.169.123"
readonly CADI_NTP_IPV6_SERVERS="fd00:ec2::123"
readonly CADI_NTP_POOLS="time.aws.com"
