#!/bin/sh

#############################################################################
##
##  virtual utm-vmm x86_64-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# VMM only supports UEFI booting

# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="tiny-power-button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="uefi"
readonly CADI_SUPPORTED_BOOTLOADERS_UEFI="grub,limine"
readonly CADI_SUPPORTED_CLOCKSOURCES="generic,acpi_pm,kvm,tsc"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="generic,hypervisor,serial"
readonly CADI_SUPPORTED_CONSOLE_GRAPHICS_DRIVERS="virtio-gpu"
readonly CADI_SUPPORTED_CONSOLE_KEYBOARD_TYPES="generic,none,usb"
readonly CADI_SUPPORTED_CONSOLE_OUTPUT_TYPES="generic,graphics,text"
readonly CADI_SUPPORTED_CRYPTO_DEVICES="virtio"
readonly CADI_SUPPORTED_DHCP_CLIENTS="generic,dhclient,dhcpcd,udhcpc"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="gpt"
readonly CADI_SUPPORTED_NETWORK_DRIVERS="virtio-net"
readonly CADI_SUPPORTED_OS_BOOT_NETWORK_DRIVERS="none"
readonly CADI_SUPPORTED_OS_DEVICE_MEDIAS="generic,disk,ssd"
readonly CADI_SUPPORTED_OS_DEVICE_TYPES="generic,nvme,virtio-blk,virtio-scsi"
readonly CADI_SUPPORTED_OS_SEPARATE_BOOT_PARTITION=true
readonly CADI_SUPPORTED_RNGS="virtio"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_BASE_NAME="ttyS"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_NUMBER="0"
readonly CADI_SUPPORTED_STORAGE_DRIVERS="generic,nvme,virtio-blk,virtio-scsi"


# Defaults
readonly CADI_DEFAULT_BOOTLOADER="grub"
readonly CADI_DEFAULT_CONSOLE_DEVICE_TYPE="generic"
readonly CADI_DEFAULT_CONSOLE_KEYBOARD_TYPE="none"
readonly CADI_DEFAULT_CONSOLE_OUTPUT_TYPE="generic"
readonly CADI_DEFAULT_DHCP_CLIENT="dhcpcd"
readonly CADI_DEFAULT_OS_DEVICE_MEDIA="generic"
readonly CADI_DEFAULT_OS_DEVICE_TYPE="virtio-blk"
readonly CADI_DEFAULT_STORAGE_DRIVER="generic"


# Additional
readonly CADI_DISK_IMAGE_FORMAT="qcow2"
