#!/bin/sh

#############################################################################
##
##  cloud outscale defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# https://docs.outscale.com/en/userguide/On-Premises-to-Cloud-Migration-Guidelines.html

# Supported
readonly CADI_SUPPORTED_ARCHS="x86_64"
readonly CADI_SUPPORTED_CLOUD_INIT_DATASOURCES="Ec2"
readonly CADI_SUPPORTED_CONFIGURATION_TOOLS="cloud-init,none"
readonly CADI_SUPPORTED_IPV4=true
readonly CADI_SUPPORTED_IPV6=false
readonly CADI_SUPPORTED_IPV4_IPV6=false
readonly CADI_SUPPORTED_NTP_METHODS="pools,servers"
readonly CADI_SUPPORTED_OS_FILESYSTEMS="ext4,xfs"


# Defaults
readonly CADI_DEFAULT_ARCH="x86_64"
readonly CADI_DEFAULT_NTP_METHOD="servers"
readonly CADI_DEFAULT_OS_FILESYSTEM="ext4"


# Additional
readonly CADI_CHRONY_INITSTEPSLEW_THRESHOLD=30
readonly CADI_CHRONY_MAKESTEP_THRESHOLD=1
readonly CADI_CHRONY_MAKESTEP_LIMIT=-1
readonly CADI_NTP_SERVERS="ntp1.outscale.net ntp2.outscale.net"
