#!/bin/sh

#############################################################################
##
##  cloud oracle x86_64-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="button,tiny-power-button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="bios,secure-uefi,uefi,hybrid"
readonly CADI_SUPPORTED_BOOTLOADERS_BIOS="grub,syslinux,limine"
readonly CADI_SUPPORTED_BOOTLOADERS_HYBRID="grub,limine"
readonly CADI_SUPPORTED_BOOTLOADERS_SECURE_UEFI="grub"
readonly CADI_SUPPORTED_BOOTLOADERS_UEFI="grub,limine"
readonly CADI_SUPPORTED_CLOCKSOURCES="acpi_pm,kvm,tsc"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="serial"
readonly CADI_SUPPORTED_CONSOLE_KEYBOARD_TYPES="none"
readonly CADI_SUPPORTED_CONSOLE_OUTPUT_TYPES="text"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="gpt,mbr"
readonly CADI_SUPPORTED_OS_DEVICE_MEDIAS="disk,ssd"
readonly CADI_SUPPORTED_OS_DEVICE_TYPES="nvme,virtio-blk,virtio-scsi"
readonly CADI_SUPPORTED_OS_SEPARATE_BOOT_PARTITION=true
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_BASE_NAME="ttyS"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_NUMBER="0"
readonly CADI_OS_NETWORK_DRIVERS="virtio_net"


# Default
readonly CADI_DEFAULT_ACPI_BUTTON="tiny-power-button"
readonly CADI_DEFAULT_BOOT_TYPE="bios"
readonly CADI_DEFAULT_BOOTLOADER="grub"
readonly CADI_DEFAULT_OS_DEVICE_MEDIA="disk"
readonly CADI_DEFAULT_OS_DEVICE_TYPE="virtio-blk"


# Additional
readonly CADI_ARCH_OPTIONAL_PACKAGES_LIST="nvme-cli"
readonly CADI_CLOUD_CLI_PACKAGES="oci-cli"
# Size of packages & all their dependencies (in MB)
readonly CADI_CLOUD_CLI_PACKAGES_SIZE=174
