#!/bin/sh
# shellcheck disable=SC2039

#############################################################################
##
##  booster-functions
##
##  Copyright 2022 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


#
# Configure booster so that only the modules necessary for the relevant
# image type are placed in the initramfs file.
#
configure_booster() {
  local _extra_files_list _fsck_programs _kernel_type
  local _modules_force_list _modules_list

  cat <<-'EOF' >> "$run_script"
	
	write_log "Configuring booster"
	{
	EOF

  _extra_files_list="/bin/busybox"
  case $image_fs_type in
    btrfs )
      _fsck_programs="/sbin/fsck.btrfs" ;;
    ext4 )
      _fsck_programs="/sbin/fsck.ext4" ;;
    f2fs )
      _fsck_programs="/usr/sbin/fsck.f2fs" ;;
    xfs )
      _fsck_programs="/sbin/fsck.xfs" ;;
  esac
  case $image_boot_type in
    secure-uefi | uefi )
      _fsck_programs="$_fsck_programs,/sbin/fsck.vfat" ;;
  esac
  if [ -n "${_fsck_programs+x}" ]; then
    _extra_files_list="$_extra_files_list,$_fsck_programs"
  fi

  _modules_list=""
  _modules_force_list="$(define_booster_base_load_modules)"

  if [ -n "${debug_enabled+x}" ]; then
    cat <<-'EOF' >> "$run_script"
	  # Debug
	  {
	    cp /etc/booster.yaml /etc/booster.yaml-orig
	  }
	
	EOF
  fi

  cat <<-EOF >> "$run_script"
	  write_log "Setting up booster.yaml" 2
	  {
	    echo "compress: gzip"
	    echo "mount_timeout: 30s"
	    echo "universal: false"
	    echo
	EOF

  if [ "$_modules_list" != "" ]; then
    cat <<-EOF >> "$run_script"
	    echo "modules: -*,${_modules_list}"
	EOF
  fi

  if [ "$_modules_force_list" != "" ]; then
    cat <<-EOF >> "$run_script"
	    echo "modules: -*"
	    echo "modules_force_load: ${_modules_force_list}"
	EOF
  fi

  if [ "$_extra_files_list" != "" ]; then
    cat <<-EOF >> "$run_script"
	    echo
	    echo "extra_files: ${_extra_files_list}"
	EOF
  fi

  if [ -n "${image_lvm_rootfs+x}" ]; then
    cat <<-EOF >> "$run_script"
	    echo
	    echo "enable_lvm: true"
	EOF
  fi

  cat <<-EOF >> "$run_script"
	  } > /etc/booster.yaml
	EOF

  if [ -n "${debug_enabled+x}" ]; then
    cat <<-'EOF' >> "$run_script"
	
	  # Debug
	  {
	    write_debug_log "booster.yaml contents:" 2
	    cat /etc/booster.yaml >> /chroot.log
	  }
	
	EOF
  fi

  _kernel_type="$(get_kernel_type)"

  cat <<-EOF >> "$run_script"
	  write_debug_log "Workaround to point /boot/initramfs-* file to /boot/booster-* file" 2
	  mkdir -p /boot/
	  ln -s /boot/booster-${_kernel_type} /boot/initramfs-${_kernel_type}
	EOF

  cat <<-'EOF' >> "$run_script"
	}
	EOF
}


#
#
#
define_booster_base_load_modules() {
  local _list

  if [ "$image_class" = "physical" ] && \
     [ "$(expr "$image_physical_type" : '.*rpi.*')" -gt 0 ]; then
    # Is a Raspberry Pi which still uses FBDEV rather than DRM
    :
  else
    # Not a Raspberry Pi
    case $image_alpine_release in
      v3.13 | v3.14 )
        # FBdev
        : ;;
      * )
        # DRM
        _list="$(module_name "kernel/drivers/gpu/drm/tiny/simpledrm.ko")" ;;
    esac
  fi

  if [ -n "${_list+x}" ];then
    _list="${_list},${image_fs_type}"
  else
    _list="${image_fs_type}"
  fi

  case $image_class in
    cloud )
      _specific_list=$(get_cloud_modules_list) ;;
    physical )
      _specific_list=$(get_physical_modules_list) ;;
    virtual )
      _specific_list=$(get_virtual_modules_list) ;;
  esac

  if [ -n "${_specific_list+x}" ];then
    _list="${_list},${_specific_list}"
  fi


  _list="${_list},$(module_name "kernel/drivers/block/virtio_blk.ko")"
  _list="${_list},$(module_name "kernel/drivers/acpi/tiny-power-button.ko")"
  _list="${_list},$(module_name "kernel/drivers/gpu/drm/vmwgfx/vmwgfx.ko")"
  _list="${_list},$(module_name "kernel/drivers/scsi/sd_mod.ko")"
  _list="${_list},$(module_name "kernel/drivers/scsi/virtio_scsi.ko")"

  ###if [ -n "${image_lvm_rootfs+x}" ]; then
  ###  _list="${_list},dm-mod,dm-snapshot"
  ###fi
  if [ -n "${image_encrypted+x}" ]; then
    _list="${_list},$(module_name "kernel/drivers/md/dm-crypt.ko")"
  fi

  echo "${_list}"
}
