#!/bin/sh -u
# shellcheck disable=SC2039

#############################################################################
##
##  cloud-functions
##
##  Copyright 2021-2022 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


#
# Create cloud Alibaba mkinitfs feature file
#
configure_mkinitfs_feature_cloud_alibaba() {
  cat <<-'EOF' >> "$run_script"
	
	  {
	    write_log "Setting up features.d/cloud-alibaba.modules" 2
	EOF

  initramfs_entry_initialise "cloud-alibaba"
  initramfs_entry_add "kernel/drivers/acpi/tiny-power-button.ko*"
  initramfs_entry_add "kernel/drivers/block/virtio_blk.ko*"
  initramfs_entry_add "kernel/drivers/virtio/virtio_pci.ko*"
  initramfs_entry_finish

  if [ -n "${debug_enabled+x}" ]; then
    cat <<-'EOF' >> "$run_script"
	
	    # Debug
	    {
	      write_debug_log "cloud-alibaba.modules contents:" 2
	      cat /etc/mkinitfs/features.d/cloud-alibaba.modules >> /chroot.log
	    }
	EOF
  fi

  cat <<-'EOF' >> "$run_script"
	  }
	EOF
}


#
# Create cloud AWS mkinitfs feature file
#
configure_mkinitfs_feature_cloud_aws() {
  cat <<-'EOF' >> "$run_script"
	
	  {
	    write_log "Setting up features.d/cloud-aws.modules" 2
	EOF

  initramfs_entry_initialise "cloud-aws"
  initramfs_entry_add "kernel/drivers/acpi/tiny-power-button.ko*"
  if [ "$image_arch" = "aarch64" ]; then
    initramfs_entry_add "kernel/drivers/gpio/gpio-pl061.ko*"
  fi
  initramfs_entry_add "kernel/drivers/net/ethernet/amazon/ena"
  case $image_os_device_type in
    nvme )
      initramfs_entry_add "kernel/drivers/nvme/host/nvme.ko*"
      ;;
    sata | scsi )
      initramfs_entry_add "kernel/drivers/scsi/sd_mod.ko*"
      initramfs_entry_add "kernel/drivers/scsi/virtio_scsi.ko*"
      ;;
  esac
  initramfs_entry_add "kernel/drivers/virtio/virtio_pci.ko*"
  initramfs_entry_finish

  if [ -n "${debug_enabled+x}" ]; then
    cat <<-'EOF' >> "$run_script"
	
	    # Debug
	    {
	      write_debug_log "cloud-aws.modules contents:" 2
	      cat /etc/mkinitfs/features.d/cloud-aws.modules >> /chroot.log
	    }
	EOF
  fi

  cat <<-'EOF' >> "$run_script"
	  }
	EOF
}


#
# Create cloud Azure mkinitfs feature file
#
configure_mkinitfs_feature_cloud_azure() {
  cat <<-'EOF' >> "$run_script"
	
	  {
	    write_log "Setting up features.d/cloud-azure.modules" 2
	EOF

  initramfs_entry_initialise "cloud-azure"
  initramfs_entry_add "kernel/drivers/acpi/tiny-power-button.ko*"
  initramfs_entry_add "kernel/drivers/hv/hv_utils.ko*"
  initramfs_entry_add "kernel/drivers/hv/hv_vmbus.ko*"
  initramfs_entry_add "kernel/drivers/net/hyperv/hv_netvsc.ko*"
  initramfs_entry_add "kernel/drivers/scsi/sd_mod.ko*"
  initramfs_entry_add "kernel/drivers/scsi/hv_storvsc.ko*"
  case $image_alpine_release in
    v3.13 | v3.14 )
      initramfs_entry_add "kernel/drivers/video/fbdev/hyperv_fb.ko*" ;;
    * )
      initramfs_entry_add "kernel/drivers/gpu/drm/hyperv/hyperv_drm.ko*" ;;
  esac
  initramfs_entry_finish

  if [ -n "${debug_enabled+x}" ]; then
    cat <<-'EOF' >> "$run_script"
	
	    # Debug
	    {
	      write_debug_log "cloud-azure.modules contents:" 2
	      cat /etc/mkinitfs/features.d/cloud-azure.modules >> /chroot.log
	    }
	EOF
  fi

  cat <<-'EOF' >> "$run_script"
	  }
	EOF
}


#
# Create cloud Exoscale mkinitfs feature file
#
configure_mkinitfs_feature_cloud_exoscale() {
  cat <<-'EOF' >> "$run_script"
	
	  {
	    write_log "Setting up features.d/cloud-exoscale.modules" 2
	EOF

  initramfs_entry_initialise "cloud-exoscale"
  initramfs_entry_add "kernel/drivers/acpi/tiny-power-button.ko*"
  initramfs_entry_add "kernel/drivers/char/hw_random/rng-core.ko*"
  initramfs_entry_add "kernel/drivers/char/hw_random/virtio-rng.ko*"
  initramfs_entry_add "kernel/drivers/net/virtio_net.ko*"
  case $image_os_device_type in
    nvme )
      initramfs_entry_add "kernel/drivers/nvme/host/nvme.ko*"
      ;;
    sata | scsi )
      initramfs_entry_add "kernel/drivers/scsi/sd_mod.ko*"
      initramfs_entry_add "kernel/drivers/scsi/virtio_scsi.ko*"
      ;;
  esac
  initramfs_entry_add "kernel/drivers/virtio/virtio_pci.ko*"
  initramfs_entry_finish

  if [ -n "${debug_enabled+x}" ]; then
    cat <<-'EOF' >> "$run_script"
	
	    # Debug
	    {
	      write_debug_log "cloud-exoscale.modules contents:" 2
	      cat /etc/mkinitfs/features.d/cloud-exoscale.modules >> /chroot.log
	    }
	EOF
  fi

  cat <<-'EOF' >> "$run_script"
	  }
	EOF
}


#
# Create cloud Google mkinitfs feature file
#
configure_mkinitfs_feature_cloud_google() {
  cat <<-'EOF' >> "$run_script"
	
	  {
	    write_log "Setting up features.d/cloud-google.modules" 2
	EOF

  initramfs_entry_initialise "cloud-google"
  initramfs_entry_add "kernel/drivers/acpi/tiny-power-button.ko*"
  initramfs_entry_add "kernel/drivers/net/virtio_net.ko*"
  case $image_os_device_type in
    nvme )
      initramfs_entry_add "kernel/drivers/nvme/host/nvme.ko*"
      ;;
    sata | scsi )
      initramfs_entry_add "kernel/drivers/scsi/sd_mod.ko*"
      initramfs_entry_add "kernel/drivers/scsi/virtio_scsi.ko*"
      ;;
  esac
  initramfs_entry_add "kernel/drivers/virtio/virtio_pci.ko*"
  initramfs_entry_finish

  if [ -n "${debug_enabled+x}" ]; then
    cat <<-'EOF' >> "$run_script"
	
	    # Debug
	    {
	      write_debug_log "cloud-google.modules contents:" 2
	      cat /etc/mkinitfs/features.d/cloud-google.modules >> /chroot.log
	    }
	EOF
  fi

  cat <<-'EOF' >> "$run_script"
	  }
	EOF
}


#
# Define default settings for Cloud
#
default_cloud_settings() {
  if [ -z ${esp_type+x} ]; then
    esp_type=$CONSTANT_CLOUD_ESP_TYPE
  fi

  if [ -z "${filename_for_image+x}" ]; then
    filename_for_image="alpine-$image_alpine_release-$image_arch-$image_class-$image_cloud_type.img"
  fi

  # AWS Encryption
  if [ -n "${image_encrypted+x}" ] && [ "$image_cloud_type" = "aws" ]; then
    error_message "For AWS you should use an encrypted EBS device!"
  fi

  # Cloud software (cloud-init por tiny-cloud)
  if [ -z "${image_cloud_software+x}" ]; then
    image_cloud_software="cloud-init"
  elif [ "$image_cloud_software" = "tiny-cloud" ]; then
    case $image_cloud_type in
      aws | azure | google | oracle )
        ;;
      * )
        error_message "tiny-cloud is not supported for this cloud provider!"
        ;;
    esac
  fi

  # NTP
  if [ -n "${image_ntp_use_host+x}" ] && \
     [ "$image_ntp_use_host" = "true" ] && \
	   [ -z "${image_experimental+x}" ]; then
    error_message "PTP/NTP host sync is currently experimental! Full support is not present in released Alpine packages."
  fi
  if [ -n "${image_ntp_servers+x}" ]; then
    error_message "NTP servers can only be specified for physical servers, other servers obtain this information from user-data!"
  fi

  # Remove encryption unlock
  if [ -n "${remote_unlock_enabled+x}" ]; then
    error_message "Remote unlocking of encrypted rootfs is not supported in cloud!"
  fi

  # Arch-specific settings
  case $image_arch in
    aarch64 )
      if [ -z "${keyboard_type+x}" ]; then
        # aarch64 VMs normally use USB keyboard
        keyboard_type="usb"
      fi
      # aarch64 Cloud VMs always use UEFI
      image_boot_type="uefi"
      if [ -n "${image_bootloader+x}" ] && \
         [ "$image_bootloader" != "grub" ]; then
          error_message "aarch64 cloud machine can only use Grub bootloader!"
      fi
      image_bootloader="grub"
      case $image_cloud_type in
        aws | azure | oracle )
          ;;
        * )
          error_message "aarch64 cloud images cannot be created for this cloud provider!"
          ;;
      esac
      ;;
    x86 | x86_64 )
      if [ -z "${keyboard_type+x}" ]; then
        keyboard_type="ps2"
      fi
      image_boot_type="bios"
      # Bootloader may be overriden below at per-cloud level
      image_bootloader="grub"
      ;;
  esac

  # Cloud-specific settings
  case $image_cloud_type in
    azure )
      image_bootloader="grub"
      keyboard_type="serial"
      if [ -n "${image_experimental+x}" ]; then
        image_ntp_use_host=true
      fi
      ;;
  esac

  if [ -z "${image_ntp_use_host+x}" ]; then
    # By default the majority of Cloud providers do not support
    # hypervisor PTP/NTP host time sync
    image_ntp_use_host=false
  fi

  # Sort out partition sizing
  #---------------------------
  case $image_arch in
    aarch64 )
      general_boot_part_size=$CONSTANT_CLOUD_AARCH64_BOOT_PART_SIZE ;;
    x86 )
      general_boot_part_size=$CONSTANT_CLOUD_X86_BOOT_PART_SIZE ;;
    x86_64 )
      general_boot_part_size=$CONSTANT_CLOUD_X86_64_BOOT_PART_SIZE ;;
  esac
  if [ -z "${general_root_part_size+x}" ]; then
    general_root_part_size=$CONSTANT_CLOUD_ROOT_PART_SIZE
  fi
  if [ -z "${esp_part_size+x}" ]; then
    general_uefi_part_size=$CONSTANT_DEFAULT_CLOUD_ESP_PART_SIZE
  else
    general_uefi_part_size=$esp_part_size
  fi
}
