#!/bin/sh

#############################################################################
##
##  disk-image-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################

# Defaults
readonly CADI_DEFAULT_ADMIN_USERNAME="alpine"
readonly CADI_DEFAULT_BOOT_REFERENCE="uuid"
readonly CADI_DEFAULT_DISK_RESIZE_FREE_PERCENT=10
readonly CADI_DEFAULT_EFI_BOOTSTUB="gummiboot"
readonly CADI_DEFAULT_FS_TYPE="ext4"
readonly CADI_DEFAULT_LUKS_CIPHER="aes-xts-plain64"
readonly CADI_DEFAULT_LUKS_PASSPHRASE="InsecureDefault"
readonly CADI_DEFAULT_SSH_KEYTYPES="ed25519"


# Filesystem labels and LVM device names
readonly CADI_BOOTFS_LABEL="boot"
readonly CADI_CIDATA_LABEL="CIDATA"
readonly CADI_ESP_FS_LABEL="SYSTEM EFI"
readonly CADI_LOGSFS_LABEL="logs"
readonly CADI_LUKS_DEVICE_NAME="lukspart"
readonly CADI_LUKS_LABEL="luks-main"
readonly CADI_LVM_BOOT_LV_NAME="boot"
readonly CADI_LVM_LOGS_LV_NAME="logs"
readonly CADI_LVM_ROOT_LV_NAME="root"
readonly CADI_LVM_VG_NAME="vg0"
readonly CADI_ROOTFS_LABEL="alpine-root"
readonly CADI_RPIBOOT_LABEL="RPIBOOT"
readonly CADI_SWAP_PART_LABEL="Swap"

# Filesystem reserved space in %
readonly CADI_BTRFS_RESERVED_PERCENT="5"
readonly CADI_EXT4_RESERVED_PERCENT="20"
readonly CADI_F2FS_RESERVED_PERCENT="40"
readonly CADI_XFS_RESERVED_PERCENT="7"

# Storage overhead for LUKS and LVM in %
readonly CADI_LUKSv1_OVERHEAD_PERCENT="4"
readonly CADI_LUKSv2_OVERHEAD_MB="16"
readonly CADI_LVM_OVERHEAD_PERCENT="7"


###########################################################################
#        Partition / filesystem sizing (in MiB)
###########################################################################

readonly CADI_CIDATA_PART_SIZE=1
# With XFS the minimum size must be 16MiB
readonly CADI_LVM_LOGS_LV_SIZE=16

# FAT32 minimum filesystem size depends on the device's sector size
#
# Minimum filesystem size on 512-byte sector device,
# 65525 clusters x 512 byte sector = 32 MiB
readonly CADI_DEFAULT_FAT32_512_ESP_PART_SIZE=32
# Minimum filesystem size on 4K sector device,
# 65525 clusters x 4096 byte sector = 256MiB
readonly CADI_DEFAULT_FAT32_4096_ESP_PART_SIZE=256
