#!/bin/sh

#############################################################################
##
##  ntp-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


readonly CADI_GENERAL_NTP_POOLS="pool.ntp.org"
readonly CADI_GENERAL_NTP_SERVERS_OPTIONS="iburst"
