#!/bin/sh

#############################################################################
##
##  virtual aarch64-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Size of Gummiboot/Stubby EFI stub file
readonly CADI_EFISTUB_SIZE=1


# linux-edge
#------------

# Installed size of the linux-edge package (in MiB)
readonly CADI_KERNEL_EDGE_PACKAGE_SIZE=109
# Size of linux-edge kernel file (in MiB)
readonly CADI_KERNEL_EDGE_FILE_SIZE=7
# Size of linux-edge System.map (in MiB)
readonly CADI_KERNEL_EDGE_SYSTEMMAP_FILE_SIZE=3
# Size of linux-edge config-edge (in MiB)
readonly CADI_KERNEL_EDGE_CONFIG_FILE_SIZE=1
# Size of linux-edge DTB files (in MiB)
readonly CADI_KERNEL_EDGE_DTB_FILES_SIZE=12
# Size of linux-edge System.map, config, DTB files, and kernel file (in MiB)
readonly CADI_BOOTFS_KERNEL_EDGE_FILES_SIZE=$((CADI_KERNEL_EDGE_SYSTEMMAP_FILE_SIZE + CADI_KERNEL_EDGE_CONFIG_FILE_SIZE + CADI_KERNEL_EDGE_DTB_FILES_SIZE + CADI_KERNEL_EDGE_FILE_SIZE))
# Size of linux-edge package files placed in rootfs rather than in /boot (i.e. kernel modules) (in MiB)
readonly CADI_ROOTFS_KERNEL_EDGE_FILES_SIZE=$((CADI_KERNEL_EDGE_PACKAGE_SIZE - CADI_BOOTFS_KERNEL_EDGE_FILES_SIZE))


# linux-virt
#------------

# Installed size of the linux-virt package (in MiB)
readonly CADI_KERNEL_VIRT_PACKAGE_SIZE=45
# Size of linux-virt kernel file (in MiB)
readonly CADI_KERNEL_VIRT_FILE_SIZE=8
# Size of linux-virt System.map (in MiB)
readonly CADI_KERNEL_VIRT_SYSTEMMAP_FILE_SIZE=3
# Size of linux-virt config-virt (in MiB)
readonly CADI_KERNEL_VIRT_CONFIG_FILE_SIZE=1
# Size of linux-virt DTB files (in MiB)
readonly CADI_KERNEL_VIRT_DTB_FILES_SIZE=12
# Size of linux-virt System.map, config, DTB files, and kernel file from kernel package (in MiB)
readonly CADI_BOOTFS_KERNEL_VIRT_FILES_SIZE=$((CADI_KERNEL_VIRT_SYSTEMMAP_FILE_SIZE + CADI_KERNEL_VIRT_CONFIG_FILE_SIZE + CADI_KERNEL_VIRT_DTB_FILES_SIZE + CADI_KERNEL_VIRT_FILE_SIZE))
# Size of linux-virt package files placed in rootfs rather than in /boot (i.e. kernel modules) (in MiB)
readonly CADI_ROOTFS_KERNEL_VIRT_FILES_SIZE=$((CADI_KERNEL_VIRT_PACKAGE_SIZE - CADI_BOOTFS_KERNEL_VIRT_FILES_SIZE))
