#!/bin/sh

#############################################################################
##
##  virtual openbsd-vmm x86-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="tiny-power-button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="bios,hybrid"
readonly CADI_SUPPORTED_BOOTLOADERS_BIOS="grub,limine,syslinux"
readonly CADI_SUPPORTED_BOOTLOADERS_HYBRID="grub,limine"
readonly CADI_SUPPORTED_CLOCKSOURCES="generic,acpi_pm,tsc"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="serial"
readonly CADI_SUPPORTED_CRYPTO_DEVICES="virtio"
readonly CADI_SUPPORTED_DHCP_CLIENTS="generic,dhclient,dhcpcd,udhcpc"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="mbr"
readonly CADI_SUPPORTED_NETWORK_DRIVERS="virtio-net"
readonly CADI_SUPPORTED_OS_BOOT_NETWORK_DRIVERS="none"
readonly CADI_SUPPORTED_OS_DEVICE_MEDIAS="disk"
readonly CADI_SUPPORTED_OS_DEVICE_TYPES="virtio-blk"
readonly CADI_SUPPORTED_RNGS="virtio"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_BASE_NAME="ttyS"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_NUMBER="0"
readonly CADI_SUPPORTED_STORAGE_DRIVERS="virtio-blk"


# Defaults
readonly CADI_DEFAULT_BOOT_TYPE="bios"
readonly CADI_DEFAULT_BOOTLOADER="grub"
readonly CADI_DEFAULT_DHCP_CLIENT="dhcpcd"


# Additional
readonly CADI_VIRTUAL_DRIVER_PACKAGES_LIST="virtio_vmmci,vmm_clock"
readonly CADI_VIRTUAL_DRIVER_PACKAGES_SIZE=1
readonly CADI_VIRTUAL_DRIVER_PACKAGES_NOTPRESENTIN="v3.13,v3.14,v3.15,v3.16,v3.17"
