#!/bin/sh

#############################################################################
##
##  virtual generic defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Supported
readonly CADI_SUPPORTED_ARCHS="aarch64,x86,x86_64"
readonly CADI_SUPPORTED_CLOUD_INIT_DATASOURCES="AltCloud,ConfigDrive,LXD,NoCloud,OpenNebula,OpenStack,OVF,VMware"
readonly CADI_SUPPORTED_CONFIGURATION_TOOLS="cloud-init,none"
readonly CADI_SUPPORTED_IPV4=true
readonly CADI_SUPPORTED_IPV6=true
readonly CADI_SUPPORTED_IPV4_IPV6=true
readonly CADI_SUPPORTED_NTP_METHODS="pools,servers"
readonly CADI_SUPPORTED_OS_FILESYSTEMS="ext4,xfs"


# Defaults
readonly CADI_DEFAULT_ARCH="x86_64"
readonly CADI_DEFAULT_CONFIGURATION_TOOL="cloud-init"
readonly CADI_DEFAULT_NTP_METHOD="servers"
readonly CADI_DEFAULT_OS_FILESYSTEM="ext4"
