#!/bin/sh

#############################################################################
##
##  cloud google aarch64-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# https://cloud.google.com/compute/docs/import/import-existing-image#prepare_boot_disk

# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="button,gpio,tiny-power-button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="secure-uefi,uefi"
readonly CADI_SUPPORTED_BOOTLOADERS_UEFI="grub"
readonly CADI_SUPPORTED_CLOCKSOURCES="acpi_pm,kvm,tsc"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="serial"
readonly CADI_SUPPORTED_CONSOLE_KEYBOARD_TYPES="none"
readonly CADI_SUPPORTED_CONSOLE_OUTPUT_TYPES="text"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="gpt"
readonly CADI_SUPPORTED_GRAPHICS_DRIVERS="simpledrm"
readonly CADI_SUPPORTED_OS_NETWORK_DRIVERS="gve"
readonly CADI_SUPPORTED_OS_SEPARATE_BOOT_PARTITION=true
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_BASE_NAME="ttyAMA"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_NUMBER="0"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_SPEED="38400"
readonly CADI_SUPPORTED_RNGS="virtio"


# Defaults
readonly CADI_DEFAULT_ACPI_BUTTON="gpio"
readonly CADI_DEFAULT_BOOT_TYPE="uefi"


# Additional
