#!/bin/sh

#############################################################################
##
##  cloud google aarch64-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# https://cloud.google.com/compute/docs/import/import-existing-image#prepare_boot_disk

# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="generic,gpio,tiny-power-button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="secure-uefi,uefi"
readonly CADI_SUPPORTED_BOOTLOADERS_SECURE_UEFI="none"
readonly CADI_SUPPORTED_BOOTLOADERS_UEFI="grub"
readonly CADI_SUPPORTED_CLOCKSOURCES="arch_sys_counter"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="serial"
readonly CADI_SUPPORTED_CONSOLE_GRAPHICS_DRIVERS="virtio-gpu"
readonly CADI_SUPPORTED_CONSOLE_KEYBOARD_TYPES="none"
readonly CADI_SUPPORTED_CONSOLE_OUTPUT_TYPES="graphics"
readonly CADI_SUPPORTED_CRYPTO_DEVICES="virtio"
readonly CADI_SUPPORTED_DHCP_CLIENTS="dhclient"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="gpt"
readonly CADI_SUPPORTED_NETWORK_DRIVERS="generic,gve,virtio-net"
readonly CADI_SUPPORTED_OS_BOOT_NETWORK_DRIVERS="none"
readonly CADI_SUPPORTED_OS_DEVICE_MEDIAS="generic,disk,ssd"
readonly CADI_SUPPORTED_OS_DEVICE_TYPES="generic,nvme,virtio-scsi"
readonly CADI_SUPPORTED_OS_SEPARATE_BOOT_PARTITION=true
readonly CADI_SUPPORTED_RNGS="virtio"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_BASE_NAME="ttyAMA"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_NUMBER="0"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_SPEED="38400"
readonly CADI_SUPPORTED_STORAGE_DRIVERS="generic,nvme,virtio-scsi"


# Defaults
readonly CADI_DEFAULT_ACPI_BUTTON="generic"
readonly CADI_DEFAULT_BOOT_TYPE="uefi"
readonly CADI_DEFAULT_NETWORK_DRIVER="generic"
readonly CADI_DEFAULT_OS_DEVICE_MEDIA="disk"
readonly CADI_DEFAULT_OS_DEVICE_TYPE="virtio-scsi"
readonly CADI_DEFAULT_STORAGE_DRIVER="generic"


# Additional
readonly CADI_DISK_IMAGE_FORMAT="raw"
readonly CADI_PACKAGES_EXTRA="nvme-cli"
# Size of package & all their dependencies (in MB)
readonly CADI_PACKAGES_EXTRA_SIZE=1
