#!/bin/sh

#############################################################################
##
##  cloud google x86-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# https://cloud.google.com/compute/docs/import/import-existing-image#prepare_boot_disk
#
# Google x86_86 only support BIOS booting via Grub and serial console

# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="tiny-power-button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="bios"
readonly CADI_SUPPORTED_BOOTLOADERS_BIOS="grub"
readonly CADI_SUPPORTED_CLOCKSOURCES="generic,acpi_pm,kvm,tsc"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="serial"
readonly CADI_SUPPORTED_CONSOLE_GRAPHICS_DRIVERS="simpledrm"
readonly CADI_SUPPORTED_CONSOLE_KEYBOARD_TYPES="none"
readonly CADI_SUPPORTED_CONSOLE_OUTPUT_TYPES="text"
readonly CADI_SUPPORTED_DHCP_CLIENTS="dhclient"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="mbr"
readonly CADI_SUPPORTED_NETWORK_DRIVERS="generic,gve,virtio-net"
readonly CADI_SUPPORTED_OS_BOOT_NETWORK_DRIVERS="none"
readonly CADI_SUPPORTED_OS_DEVICE_MEDIAS="generic,disk,ssd"
readonly CADI_SUPPORTED_OS_DEVICE_TYPES="generic,nvme,virtio-scsi"
readonly CADI_SUPPORTED_OS_SEPARATE_BOOT_PARTITION=true
readonly CADI_SUPPORTED_RNGS="virtio"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_BASE_NAME="ttyS"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_NUMBER="0"
readonly CADI_SUPPORTED_SERIAL_CONSOLE_PORT_SPEED="38400"
readonly CADI_SUPPORTED_STORAGE_DRIVERS="generic,nvme,virtio-scsi"


# Defaults
readonly CADI_DEFAULT_NETWORK_DRIVER="generic"
readonly CADI_DEFAULT_OS_DEVICE_MEDIA="disk"
readonly CADI_DEFAULT_OS_DEVICE_TYPE="virtio-scsi"
readonly CADI_DEFAULT_STORAGE_DRIVER="generic"


# Additional
readonly CADI_DISK_IMAGE_FORMAT="raw"
readonly CADI_PACKAGES_EXTRA="nvme-cli"
# Size of package & all their dependencies (in MB)
readonly CADI_PACKAGES_EXTRA_SIZE=1
