#!/bin/sh

#############################################################################
##
##  physical aarch64-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Size of Gummiboot/Stubby EFI stub file
readonly CADI_EFI_STUB_SIZE=1


# linux-edge
#------------

# Installed size of the linux-edge package (in MiB)
readonly CADI_KERNEL_EDGE_PACKAGE_SIZE=109
# Size of linux-edge kernel file (in MiB)
readonly CADI_KERNEL_EDGE_FILE_SIZE=7
# Size of linux-edge System.map (in MiB)
readonly CADI_KERNEL_EDGE_SYSTEMMAP_FILE_SIZE=3
# Size of linux-edge config-edge (in MiB)
readonly CADI_KERNEL_EDGE_CONFIG_FILE_SIZE=1
# Size of linux-edge DTB files (in MiB)
readonly CADI_KERNEL_EDGE_DTB_FILES_SIZE=12
# Size of linux-edge System.map, config, DTB files, and kernel file (in MiB)
readonly CADI_BOOTFS_KERNEL_EDGE_FILES_SIZE=$((CADI_KERNEL_EDGE_SYSTEMMAP_FILE_SIZE + CADI_KERNEL_EDGE_CONFIG_FILE_SIZE + CADI_KERNEL_EDGE_DTB_FILES_SIZE + CADI_KERNEL_EDGE_FILE_SIZE))
# Size of linux-edge package files placed in rootfs rather than in /boot (i.e. kernel modules) (in MiB)
readonly CADI_ROOTFS_KERNEL_EDGE_FILES_SIZE=$((CADI_KERNEL_EDGE_PACKAGE_SIZE - CADI_BOOTFS_KERNEL_EDGE_FILES_SIZE))


# linux-lts
#-----------

# Installed size of the linux-lts package (in MiB)
readonly CADI_KERNEL_LTS_PACKAGE_SIZE=103
# Size of linux-lts kernel file (in MiB)
readonly CADI_KERNEL_LTS_FILE_SIZE=7
# Size of linux-lts System.map (in MiB)
readonly CADI_KERNEL_LTS_SYSTEMMAP_FILE_SIZE=3
# Size of linux-lts config-lts (in MiB)
readonly CADI_KERNEL_LTS_CONFIG_FILE_SIZE=1
# Size of linux-lts DTB files (in MiB)
readonly CADI_KERNEL_LTS_DTB_FILES_SIZE=12
# Size of linux-lts System.map, config, DTB files, and kernel file (in MiB)
readonly CADI_BOOTFS_KERNEL_LTS_FILES_SIZE=$((CADI_KERNEL_LTS_SYSTEMMAP_FILE_SIZE + CADI_KERNEL_LTS_CONFIG_FILE_SIZE + CADI_KERNEL_LTS_DTB_FILES_SIZE + CADI_KERNEL_LTS_FILE_SIZE))
# Size of linux-lts package files placed in rootfs rather than in /boot (i.e. kernel modules) (in MiB)
readonly CADI_ROOTFS_KERNEL_LTS_FILES_SIZE=$((CADI_KERNEL_LTS_PACKAGE_SIZE - CADI_BOOTFS_KERNEL_LTS_FILES_SIZE))


# linux-rpi
#-----------

# Installed size of the linux-rpi package (in MiB)
readonly CADI_KERNEL_RPI_PACKAGE_SIZE=103
# Size of linux-rpi kernel file (in MiB)
readonly CADI_KERNEL_RPI_FILE_SIZE=7
# Size of linux-rpi System.map (in MiB)
readonly CADI_KERNEL_RPI_SYSTEMMAP_FILE_SIZE=3
# Size of linux-rpi config-rpi (in MiB)
readonly CADI_KERNEL_RPI_CONFIG_FILE_SIZE=1
# Size of linux-rpi DTB files (in MiB)
readonly CADI_KERNEL_RPI_DTB_FILES_SIZE=12
# Size of linux-rpi System.map, config, DTB files, and kernel file (in MiB)
readonly CADI_BOOTFS_KERNEL_RPI_FILES_SIZE=$((CADI_KERNEL_RPI_SYSTEMMAP_FILE_SIZE + CADI_KERNEL_RPI_CONFIG_FILE_SIZE + CADI_KERNEL_RPI_DTB_FILES_SIZE + CADI_KERNEL_RPI_FILE_SIZE))
# Size of linux-rpi package files placed in rootfs rather than in /boot (i.e. kernel modules) (in MiB)
readonly CADI_ROOTFS_KERNEL_RPI_FILES_SIZE=$((CADI_KERNEL_RPI_PACKAGE_SIZE - CADI_BOOTFS_KERNEL_RPI_FILES_SIZE))


# linux-rpi4
#------------

# Installed size of the linux-rpi4 package (in MiB)
readonly CADI_KERNEL_RPI4_PACKAGE_SIZE=103
# Size of linux-rpi4 kernel file (in MiB)
readonly CADI_KERNEL_RPI4_FILE_SIZE=7
# Size of linux-rpi4 System.map (in MiB)
readonly CADI_KERNEL_RPI4_SYSTEMMAP_FILE_SIZE=3
# Size of linux-rpi4 config-rpi4 (in MiB)
readonly CADI_KERNEL_RPI4_CONFIG_FILE_SIZE=1
# Size of linux-rpi4 DTB files (in MiB)
readonly CADI_KERNEL_RPI4_DTB_FILES_SIZE=12
# Size of linux-rpi4 System.map, config, DTB files, and kernel file (in MiB)
readonly CADI_BOOTFS_KERNEL_RPI4_FILES_SIZE=$((CADI_KERNEL_RPI4_SYSTEMMAP_FILE_SIZE + CADI_KERNEL_RPI4_CONFIG_FILE_SIZE + CADI_KERNEL_RPI4_DTB_FILES_SIZE + CADI_KERNEL_RPI4_FILE_SIZE))
# Size of linux-rpi4 package files placed in rootfs rather than in /boot (i.e. kernel modules) (in MiB)
readonly CADI_ROOTFS_KERNEL_RPI4_FILES_SIZE=$((CADI_KERNEL_RPI4_PACKAGE_SIZE - CADI_BOOTFS_KERNEL_RPI4_FILES_SIZE))
