#!/bin/sh

#############################################################################
##
##  physical x86_64-barebones-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Size of firmware files for barebones
readonly CADI_FIRMWARE_SIZE=50
# Size of microcode files for barebones
readonly CADI_MICROCODE_SIZE=20

# Size of initramfs for barebones
readonly CADI_INITRAMFS_SIZE=5

# Arbitrary "base" size of barebones rootfs (in MB)
readonly CADI_ARBITRARY_ROOTFS_SIZE=350

# Size of Grub files in /boot
readonly CADI_BOOTLOADER_GRUB_BOOT_FILES_SIZE=3
# Size of Limine files in /boot
readonly CADI_BOOTLOADER_LIMINE_BOOT_FILES_SIZE=1
# Size of Syslinux files in /boot
readonly CADI_BOOTLOADER_SYSLINUX_BOOT_FILES_SIZE=1

# Size of files in rootfs except for kernel package
readonly CADI_ROOTFS_SIZE=$((CADI_ARBITRARY_ROOTFS_SIZE - CADI_KERNEL_PACKAGE_SIZE))

# Size of an ESP partition/FAT fs containing a UKI file made up of EFI stub, kernel, initramfs, and microcode for barebones
readonly CADI_DEFAULT_UKI_ESP_PART_SIZE=$((CADI_EFI_STUB_SIZE + CADI_KERNEL_FILE_SIZE + CADI_INITRAMFS_SIZE + CADI_MICROCODE_SIZE))
