#!/bin/sh

#############################################################################
##
##  cloud ovh defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Supported
readonly CADI_SUPPORTED_ARCHS="x86_64"
readonly CADI_SUPPORTED_DISK_IMAGE_CLOUD_INIT_DATASOURCES="ConfigDrive"
readonly CADI_SUPPORTED_CONFIGURATION_TOOLS="cloud-init,none"
readonly CADI_SUPPORTED_IPV4=true
readonly CADI_SUPPORTED_IPV6=true
readonly CADI_SUPPORTED_IPV4_IPV6=true
readonly CADI_SUPPORTED_NTP_METHODS="pools,servers"
readonly CADI_SUPPORTED_OS_FILESYSTEMS="ext4,xfs"


# Defaults
readonly CADI_DEFAULT_OS_FILESYSTEM="ext4"


# Additional
