#!/bin/sh

#############################################################################
##
##  cloud ovh x86_64-defines
##
##  Copyright 2021-2023 Dermot Bradley <dermot_bradley@yahoo.com>
##
##  Licensed via GPL version 2.0
##
#############################################################################


# Supported
readonly CADI_SUPPORTED_ACPI_BUTTONS="button,tiny-power-button"
readonly CADI_SUPPORTED_BOOT_REFERENCES="device,label,uuid"
readonly CADI_SUPPORTED_BOOT_TYPES="bios,uefi"
readonly CADI_SUPPORTED_BOOTLOADERS_BIOS="grub,syslinux,limine"
readonly CADI_SUPPORTED_BOOTLOADERS_UEFI="grub,limine"
readonly CADI_SUPPORTED_CLOCKSOURCES="acpi_pm,kvm,tsc"
readonly CADI_SUPPORTED_CONSOLE_DEVICE_TYPES="normal"
readonly CADI_SUPPORTED_CONSOLE_GRAPHICS_DRIVERS="bochs,simpledrm"
readonly CADI_SUPPORTED_CONSOLE_KEYBOARD_TYPES="ps2"
readonly CADI_SUPPORTED_CONSOLE_OUTPUT_TYPES="graphics,text"
readonly CADI_SUPPORTED_DISK_IMAGE_COMPRESSIONS="bzip2,gzip"
readonly CADI_SUPPORTED_DISK_IMAGE_PARTITIONING_TYPES="gpt,mbr"
readonly CADI_SUPPORTED_OS_DEVICE_MEDIAS="disk,ssd"
readonly CADI_SUPPORTED_OS_DEVICE_TYPES="nvme,virtio-blk,virtio-scsi"
readonly CADI_SUPPORTED_OS_BOOT_NETWORK_DRIVERS="virtio_net"
readonly CADI_SUPPORTED_OS_NETWORK_DRIVERS="virtio_net"
readonly CADI_SUPPORTED_OS_SEPARATE_BOOT_PARTITION=true


# Defaults
readonly CADI_DEFAULT_ACPI_BUTTON="tiny-power-button"
readonly CADI_DEFAULT_BOOT_TYPE="bios"
readonly CADI_DEFAULT_BOOTLOADER="grub"
readonly CADI_DEFAULT_CONSOLE_OUTPUT_TYPE="text"
readonly CADI_DEFAULT_OS_DEVICE_MEDIAS="disk"
readonly CADI_DEFAULT_OS_DEVICE_TYPES="virtio-blk"


# Additional
readonly CADI_DISK_IMAGE_FORMAT="qcow2"
