version: 2
ethernets:
  eth0:
    match:
      macaddress: '52:54:00:12:34:56'
      name: eth0
    addresses:
      - 192.168.1.2/24
    gateway4: 192.168.1.1
    nameservers:
      addresses: [ 192.168.1.1 ]

