#cloud-config

apk_repos:
  preserve_repositories: false
  alpine_repo:
    base_url: 'https://alpine.global.ssl.fastly.net/alpine/'
    community_enabled: true
    testing_enabled: false
    # Specify either "edge" or "v<release number", i.e. "v3.14"
    version: 'v3.14'
  #local_repo_base_url: 'https://<your-server>/local-alpine'

debug:
  verbose: false

#disable_ec2_metadata: true

growpart:
  mode: auto
  ignore_growroot_disabled: true

ssh_fp_console_blacklist: [ "ssh-ed25519" ]
ssh_key_console_blacklist: [ "ssh-ed25519" ]

locale: en_GB
locale_configfile: /etc/profile.d/locale.sh

ntp:
  enabled: true
  servers:
    - pool.ntp.org

package_reboot_if_required: false
package_update: true
package_upgrade: false
#packages:
#  - <package name>
#  - <package name>

resize_rootfs: true

manage_resolv_conf: true
resolv_conf:
  domain: <your domain>
  nameservers: ['192.168.1.1']
  #options:
  #  rotate: true
  #  timeout: 1

#rsyslog:
#  config_dir: /etc/rsyslog.d
#  config_filename: 20-cloud-config.conf
#  configs:
#    - "*.* @@192.168.1.7"
#    - content: "*.*   @@192.168.1.5:10514"
#      filename: 01-example.conf
#    - content: |
#        *.*   @@syslogd.example.com
#  remotes:
#    central-syslog: "@192.168.1.6"
#  service_reload_command: [service, rsyslog, restart]

#runcmd:
#  # Prevent cloud-init running again after 1st boot
#  - rm -f /etc/runlevels/boot/cloud-init-local
#  - rm -f /etc/runlevels/default/cloud-config
#  - rm -f /etc/runlevels/default/cloud-init
#  - rm -f /etc/runlevels/default/cloud-final

#chpasswd:
#  list: |
#    root:RANDOM

# Set the password of the default user account
password: test

ssh_pwauth: false

#ssh_authorized_keys:
#    - <insert SSH public key here>

ssh_deletekeys: false
ssh_genkeytypes: [ "ed25519" ]

disable_root: true

no_ssh_fingerprints: true

timezone: Europe/London

manage_etc_hosts: true

fqdn: <your-hostname>.<your-domain-name>
preserve_hostname: false

groups:
  - admin
  - sudo

users:
  - default
  - name: other
    gecos: Other Admin
    groups: admin
    passwd: <encrypted password goes here>
    ssh_authorized_keys:
      - <insert SSH public key here>
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]

